### ISSUE TITLE
Fetch, parse, sanitize, templatize and sew back into the manuscript.

### ISSUE THREAD

**Issue by marvindanig** [marvindanig/pinocchio#1]
@craigleat 

I was thinking if we could parse the book off Gutenberg (from the appropriate endpoint) using a node utility tool? Basically the idea would be to GET the book, strip off unwanted markup, sanitize/reinsert/reformat according to the bookiza [template](https://github.com/marvindanig/The-Adventures-Of-Pinocchio/tree/master/templates) and then sew it back into the `manuscript/*`. 

The more refined the parser becomes, the better it gets! 💯

**Comment by judag** [comment]
Hi!!! 
Do you have someone else to do the book?
I'll fell better now but  I understand that this time I  delay too much  so it is ok that you ask for help, just let me know  if a continue with this proyect...:) 
Thanks for all specially for the pacient and your understanding and concern!!! :) 
Cheers!!! :) 
Judith

Date: Thu, 28 Apr 2016 14:40:14 -0700

**Comment by ghost** [comment]
@judag I hope you stay involved :-) From what I understand we have a small team bringing different skills and time commitments are flexible. I am impressed with your animation work and look forward to seeing what you can do for Pinocchio!
@marvindanig a node based page generator sounds cool.

**Comment by marvindanig** [comment]
@judag oh yes... we love your work! Waiting for your art on Pinocchio! 👍 

@craigleat such a tool can be used to stitch up a book from any page/file we want! 😎 

Have you seen [x-rays](https://github.com/lapwinglabs/x-ray) & [cheerios](https://github.com/cheeriojs/cheerio)?

**Comment by ghost** [comment]
A parser/generator built into bookiza is essential. Imagine a long manuscript, you change the font/margins/whatever in the template and your content overflows the viewport. You then need an easy way to regenerate all the pages ensuring there's no overflow. This will involve checking the height of the content against a known viewport height and breaking the pages as appropriate. Sounds doable :)

**Comment by marvindanig** [comment]
> Imagine a long manuscript, you change the font/margins/whatever in the template and your content overflows the viewport...
> 
> Sounds doable :)

Yep, it is! and it's going to be fun. 

I view it more like a module that can be had on the book's `package.json` -- and not directly built into Bookiza itself. Two reasons for that:  
- The act of creation, configuration and server setup of the project (the container) has almost nothing to do with content. A greeting card artist, comics artist or a fashion magazine creator will, for example, not  (never?) need such a thing.
-  Turning bookiza into a large monolith seems like an unsustainable approach in the long term. Ideally, it'd have to be broken down into smaller (not too small like those one line modules these days!) packages that are easier to juggle with.

The question right now is what name be given to the new module? 🔢 parmesanJS? oreganoJS? milkJS? 💃

**Comment by ghost** [comment]
// This is hilarious, have you noticed how your emoji change between gmail and GH?

> what name be given to the new module?

I like [proofingJS](https://en.wikipedia.org/wiki/Proofing_%28baking_technique%29) because I imagine a work surface where I prepare the dough (hack the source) and a baking tray(s) alongside where the shaped dough is placed to prove.

**Comment by judag** [comment]
Hi!!! 
Thanks a lot for your kind words!!! :)  I'am glad to be part of this great team!!! I have to be updated to know to work :) 

Judith
Date: Fri, 29 Apr 2016 00:21:43 -0700

**Comment by judag** [comment]
Please can you guide me. I'm a little lost after so many days without working on this :) 
Thanks and cheers!!! :) 

Judith

Date: Fri, 29 Apr 2016 06:45:41 -0700

**Comment by marvindanig** [comment]
Yeah, I know ... email parsers are sadly still in the 1990s!

Proofing in baking process an interesting dig but it still hints more at proofreading something than the baking process. And even then the latter would be a process of the container. Since content is the cheese, I see it more like CheeseJS. But that name is taken :(

**Comment by ghost** [comment]
Progress update:
I have a working prototype :-) It's now able to generate a complete manuscript and you can watch the book grow and shrink as you fiddle with the template.There are still some issues to be ironed out, but it's looking promising.

**Comment by marvindanig** [comment]
😄  Wicked awesome! 👯 👯 

> There are still some issues to be ironed out, but it's looking promising.

I suggest you check it into a fresh repository and publish it like a separate npm module. Feel free to add me as a collaborator! 

This package can be used to convert any web page into a reusable manuscript. In the meantime I've raised a service request with the npm registry for CheeseJS; it's currently unavailable but not being used for any package either. Iff the name comes by, we can soon call the new module cheeseJS and use it to pour all the cheese into our superbooks! 🍕 🍕 🍕 🍕

**Comment by ghost** [comment]
Auto generated 275 pages with page numbers in +- 30 seconds! (Your mileage may vary if fonts need to download.)

Take a look. The book is definitely usable without editing, but there's room for improvement.

**Comment by marvindanig** [comment]
Awesome! 

I pulled the latest changes and got 280 pages (last one is blank) in there. Have you checked in the parser/splitter JS of knead? Because I see just the original HTML of the book and a package.json in there.

**Comment by marvindanig** [comment]
One thing about inserting page numbers into content is that it conflicts with the model of having a very loose & dynamic manuscript. Page numbers are really not a part of the story/content and that's why we adopted the _page_number_switch_  at render level i.e. book in its final shape. We can do page_numbers from bubblin. Also the print standard is to count page numbers from the cover itself, so presenting sixth page as the first one is incorrect. 

Can you leave out the page numbers from the manuscript?
